### ISSUE TITLE
根据大佬的runpod api调用，写了个telegram bot

### ISSUE THREAD

**Issue by chunzhimoe** [kale5195/automatic-chillout#11]
https://github.com/chunzhimoe/chilloutai-bot
希望可以帮到大家，也相当于多一种部署方式吧！

**Comment by kale5195** [comment]
强！但我感觉 runpod 出图有点贵，最近一个朋友给我推荐了另外一个便宜的服务，我没太有时间调试

你有兴趣进入我的 slack 交流一下吗？  https://dub.sh/bot007 进来找admin就行
