### ISSUE TITLE
Chilloutmix不可见

### ISSUE THREAD

**Issue by kirinmin** [kale5195/automatic-chillout#4]

**Comment by anminnuo** [comment]
Chilloutmix现在不可见了，我搭好了环境现在差模型，请问您方便共享一下吗

**Comment by kale5195** [comment]
啊，被下架了吗？我今天看一下

不过你可以进入我的这个docker image ：chilloutai/auto-api:1.0.0 里边，下载出来...

**Comment by kale5195** [comment]
可以用这个 https://github.com/kale5195/automatic-chillout/blob/main/web-ui-zh.md 方式试试
