### ISSUE TITLE
请问在runpod跑起来十分钟，worker一直处在构建中，接收到的log也是一直在队列中正常吗

### ISSUE THREAD

**Issue by OWRIG** [kale5195/automatic-chillout#5]

**Comment by OWRIG** [comment]
报错 exec FROM failed: No such file or directory

**Comment by kale5195** [comment]
你是要对外提供API服务吗？不是的话，可以不用worker，直接用 stable diffusion webui 就行，我今天写个教程

另外你的错误是用我的那个docker image 产生的吗？

**Comment by OWRIG** [comment]
好的
是的

**Comment by OWRIG** [comment]
[FATAL tini (7)] exec FROM failed: No such file or directory，用的是项目里的dockerfile

**Comment by kale5195** [comment]
可以用这个 https://github.com/kale5195/automatic-chillout/blob/main/web-ui-zh.md 方式试试

**Comment by OWRIG** [comment]
感谢🙏

**Comment by OWRIG** [comment]
请问下大佬是怎么到第六步的，我这里从connect打开web ui进入的是终端界面，而不是最后一张图片那样。

**Comment by OWRIG** [comment]
成功了，感谢！
