### ISSUE TITLE
webui

### ISSUE THREAD

**Issue by wlwllq** [kale5195/automatic-chillout#6]
请问在runpod webui下使用你的template时如何添加新的lora模型啊

**Comment by kale5195** [comment]
可以 ssh 进入主机，把 lora 添加到 /workspace/stable-diffusion-webui/models/Lora/ 目录下，可以使用 runpod 自己的cli上传，也可以通过其他网盘sync进去

**Comment by wlwllq** [comment]
可以使用 runpod 自己的cli上传,这个可以稍微讲一下怎么操作吗

**Comment by kale5195** [comment]
可以参考这里的教程： https://github.com/runpod/runpodctl

具体就是本地安装好了 runpodctl 后，输入 `runpodctl send 文件名` ， 会有个提示

另外一个terminal，ssh 进入主机，根据提示 receive 就行
