### ISSUE TITLE
从 civikit 中 copy generation data 复制的参数，通过如何在 RunPod Serverless API的方式传递参数呢

### ISSUE THREAD

**Issue by jb522185660** [kale5195/automatic-chillout#7]
从 civikit 中 copy generation data 复制的参数，通过如何在 RunPod Serverless API的方式传递参数呢

**Comment by kale5195** [comment]
你需要自己分解成 stable diffusion web ui api需要的参数的

可以看这个文档 https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API

**Comment by jb522185660** [comment]
那就没那么方便了
