### ISSUE TITLE
有没有可能部署在国内服务器上

### ISSUE THREAD

**Issue by jb522185660** [kale5195/automatic-chillout#8]
因为国内的gpu服务器很难访问外网，我在自己电脑docker pull chilloutai/chilloutmix-template:1.2.0下载镜像以后，打包镜像文件上传到服务器再加载可以吗？具体有没有教程？

**Comment by kale5195** [comment]
可以的，就是一个普通的docker file, 你上传上去后，直接docker run  chilloutai/chilloutmix-template:1.2.0 就行，可以加参数对外开放端口
